### ISSUE TITLE
Can't add a file local variable

### ISSUE THREAD

**Issue by DamienCassou** [NicolasPetton/nroam#13]
In an org-roam buffer managed by nroam, type `M-x add-file-local-variable RET ispell-local-dictionary RET "french" RET`.

- Expected: a few lines added at the end of my buffer to remember I want spelling of this file to be checked against the French dictionary.
- Actual: an error message "Text is read-only".

### Workaround

Temporarily disable `nroam-mode`

**Comment by Whil-** [comment]
I'm only thinking out loud here... Given how nroam is designed with a separate block of text in the end of the buffer, it seems to me that nroam itself cannot solve for all the solutions where some external (to nroam) code needs to insert text at the end of the buffer.

Maybe some generic instructions for this is needed in the documentation? With hint on some ways to work around it? (Maybe with using nroam in pre and post hooks? But that there will never be a way for nroam to cater to all the external code that wants to do things at the end of the buffer?

**Comment by NicolasPetton** [comment]
I think https://github.com/Kinneyzhang/gkroam has a workaround for issues like this. They insert an extra `\n` at the end of the buffer, after the read-only section.

Another way would be to leave the nroam sections in read-write mode, but I'm not sure I'd like that.

**Comment by Whil-** [comment]
Again, only thinking out loud below... ;-)

IF nroam had an end delimiter of some kind, that could possibly also enable heading level references to be inserted into the buffer at the respective headings if they are referenced.. Removing read only makes sense if there is some fancy transclusion involved. Complexity trap. Not worth it imo.

**Comment by NicolasPetton** [comment]
@Whil- I ended up adding an extra `\n` after the sections. I've tried it in several situations and it fixes a couple of annoying issues.

**Comment by DamienCassou** [comment]
Thank you @NicolasPetton.
