### ISSUE TITLE
Unlinked references do not work on Termux/Android

### ISSUE THREAD

**Issue by emacsomancer** [NicolasPetton/nroam#25]
I don't think there's probably anything to do about this one, but using Emacs under Termux on Android, (where Org-Roam, `sqlite`, and `rg`/ripgrep all work), Unlinked References in `nroam` aren't shown, but rather a message is displayed:

    "rg" must be compiled with PCRE2 support

(Obviously this is an issue with `rg` on Termux rather than an `nroam` issue. I assume.)

**Comment by NicolasPetton** [comment]
This is a limitation of org-roam unfortunately, so there's nothing I can do about it.

**Comment by NicolasPetton** [comment]
I'm closing this one as I don't think there's anything we can do here.

**Comment by emacsomancer** [comment]
I agree. Was really just filling so that it's "documented" somewhere.
